### ISSUE TITLE
Improve how we store credentials

### ISSUE THREAD

**Issue by kingdido999** [BugSwarm/bugswarm#14]
If I understand it correctly, we currently store credentials locally in a python file, which is included in the version control. I think it makes dev work a bit awkward because we need to make sure not to include that credentials file into commit...

The standard practice is to have a placeholder config file in version control, after clones the repo, the user will need to copy and rename the config file to something that is ignored by git, and fill in credentials. For example:

- `env.example` (included in version control)
- `env.dev` (development credentials, not included in version control)
- `env.prod` (production credentials, not included in version control)

Let me know if it makes more sense than our current approach.

**Comment by octaviocorona** [comment]
Migrating issue.
