### ISSUE TITLE
Minor problems in README for Setting up BugSwarm

### ISSUE THREAD

**Issue by lxylxy123456** [BugSwarm/bugswarm#21]
1. In "Depending on where you cloned the repository, change to the database directory:", `$ cd ~/bugswarm/database` should be `$ cd bugswarm/database`; maybe add `cd ../..` at the end. 
2. [optional] Maybe in “Install MongoDB - Why MongoDB? (Optional)” add some descriptions about why it is optional (i.e. can be replaced by Docker container)
3. [optional] Can we start the database image from https://hub.docker.com/_/mongo instead of `ubuntu:16.04`?
4. [optional] Can we push the MongoDB database (tag `bugswarm-db`) to dockerhub?

**Comment by dtomassi** [comment]
Hi @lxylxy123456! Thanks for opening the issue!

1. Nice find. We can remove `~/` and make it `$ cd bugswarm/database`. What do you mean by adding `cd ../..` at the end?
2. Sure. We can add some descriptions on why it is optional.
3. I am unsure. You can try it yourself to find out.
4. You can push the Docker image to your own repository on Docker Hub if you would like.

**Comment by lxylxy123456** [comment]
@dtomassi 
1. I just created https://github.com/BugSwarm/bugswarm/pull/22 , PTAL.
2. Thanks.
3. This should be a improvement of lower priority.
4. I am just thinking this can avoid building the database image when someone wants to try it out. Low priority either.

**Comment by lxylxy123456** [comment]
1 is solved in #22
2 is no longer valid since docker is required
3 and 4 are of low priority
Closing this issue now.
